### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by Molier** [kochsebastian/ChessVisionBot#3]
all the links to files in the project are absolute paths, so one must manually change them all. fe: game_state_classes.py line 47

**Comment by kochsebastian** [comment]
That's unfortunate, please open a PR and I accept the change

**Comment by kochsebastian** [comment]
Issue has been resolved with commit [c4b6219](https://github.com/kochsebastian/ChessVisionBot/commit/c4b6219e156e2cea3aca4017fb36a1773e862cd7)
