### ISSUE TITLE
Tensorflow SavedModel loading error

### ISSUE THREAD

**Issue by yousufcodes786** [kochsebastian/ChessVisionBot#5]
kTraceback (most recent call last):
  File "main.py", line 272, in <module>
    ml_model.init_binary()
  File "/home/kali/ChessVisionBot/code/ml_model.py", line 10, in init_binary
    binary_model = load_model(model_path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: /home/kali/ChessVisionBot/model_binary/binarymodel.h5/{saved_model.pbtxt|saved_model.pb}

while try to use in my kali vm it gives me this error  , please help me to resolve this

**Comment by yousufcodes786** [comment]
import tensorflow as tf
>>> print(tf.__version__)
2.2.0
>>>

**Comment by kochsebastian** [comment]
That's the problem! This model vs build with tensorflow 1.15, which makes it incompatible with tensorflow 2.
The easiest solution would be just to downgrade tensorflow in your venv to tf 1.15. If you don't want to do that (but I don't see no reason why not to do it) you could maybe convert the .h5 and .hd5f files to a model.pb file which seems to be accepted by tensorflow 2.0

**Comment by nirmalveer** [comment]
I am on tensor flow 1.15, i am still getting the same OSError

**Comment by kochsebastian** [comment]
Closing because issue becoming stale
