### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by nirmalveer** [kochsebastian/ChessVisionBot#7]
`
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:/Users/LiveL/Desktop/ChessVisionBot-master/code/main.py", line 59, in start_playing
    found_chessboard, position  = chessboard_detection.find_chessboard()
  File "C:\Users\LiveL\Desktop\ChessVisionBot-master\code\chessboard_detection.py", line 72, in find_chessboard
    is_found, current_chessboard_image,minX,minY,maxX,maxY,test_image = find_chessboard_from_image(img)
  File "C:\Users\LiveL\Desktop\ChessVisionBot-master\code\chessboard_detection.py", line 109, in find_chessboard_from_image
    bin, contours, _hierarchy = cv2.findContours(bin, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
`

**Comment by nirmalveer** [comment]
do i change the code or the opencv version?

**Comment by kochsebastian** [comment]
What opencv version are you using?

**Comment by nirmalveer** [comment]
opencv-contrib-python-headless 4.2.0.34

**Comment by kochsebastian** [comment]
As you can see in [requirements.txt](https://github.com/kochsebastian/ChessVisionBot/blob/master/requirements.txt) or [environment.yml](https://github.com/kochsebastian/ChessVisionBot/blob/master/environment.yml) I was using opencv 3.4. 
Maybe there was a change in the findContours() function you are free to change the code and stay with opencv 4.2 but there maybe other versioning problems then

**Comment by nirmalveer** [comment]
Do you have a discord where I can directly chat with you? I have a few more questions

**Comment by kochsebastian** [comment]
I won't hold your hand while you set this project especially not with these easy questions. Try to learn to read error messages and you can fix problems by yourself
