### ISSUE TITLE
How do you detect the pieces?

### ISSUE THREAD

**Issue by PeterGardas** [kochsebastian/ChessVisionBot#8]
I am asking this because I have been going thru your source code for a couple of hours and I am perplexed. How do you detect where are the pieces from the screenshot? 

Thanks for answering.

Peter

**Comment by PeterGardas** [comment]
That is really interesting. I tried the pyautogui.locateOnScreen but i fould it unreliable. A CNN is probably a solution. Is your classifying CNN able to run on CPU or do you need a proper graphics card?

**Comment by kochsebastian** [comment]
CPU is fine, just slower

**Comment by PeterGardas** [comment]
Also, I am just curious, is there a source code of this tensorflow model in this repository? I am working on a similar program to yours and I want to be able to really look under the hood.

Regards.

Peter

**Comment by kochsebastian** [comment]
As I said the models are in their respective folders. I even put an image of their structure into the folder. If you want to examine them further feel free to load them into keras and analyze them

**Comment by PeterGardas** [comment]
Oh. I am really sorry. Thanks for the help!
